### PR TITLE
chore: Update SFDC REST api to v60 (Spring 24release)

### PR DESCRIPTION
**Pull request by jaredgj**
Would like to Update the REST API to it's latest version.

### CODE REVIEW

**Comment by pnadolny13** [comment]
@jaredgj thanks for the PR! Have you been able to verify in the API changelog about whether there are any breaking changes between API versions? Or have you tested the tap with your change and had success? I see we are on Winter 22' so this upgrades 7 releases but I have no idea how much changes between releases.

**Comment by jaredgj** [comment]
@pnadolny13 Great questions, I've been able to test the tap change and it has not broken my existing jobs. As sfor the breaking changes here are the [release notes](https://help.salesforce.com/s/articleView?id=release-notes.rn_api.htm&release=248&type=5) and the [v60 release notes](https://help.salesforce.com/s/articleView?id=release-notes.rn_api_rest.htm&release=248&type=5). No breaking changes I can see save for `Apex REST API HTTP ACCEPT headers now default to JSON` which doesn't seem breaking.

**Comment by jaredgj** [comment]
@pnadolny13 does my above answer suffice?

**Comment by pnadolny13** [comment]
@jaredgj thanks for sharing those links. I also browsed through them and didnt see anything that would cause a breaking change. That and the fact that you've been able to run it without issues seems like we should be good to merge this.

**Review by pnadolny13 — APPROVED** [review]

**Pull request merged**
